---
- name: Create Wordlist directory
  file:
    path: "{{ wordlist_path }}"
    state: directory

- name: Download Top304Thousand-probable-v2.txt
  get_url:
    dest: "{{ wordlist_path }}"
    url: https://github.com/berzerk0/Probable-Wordlists/raw/master/Real-Passwords/Top304Thousand-probable-v2.txt

- name: Download FuzzDB
  become: true
  git:
    repo: https://github.com/fuzzdb-project/fuzzdb.git
    dest: "{{ wordlist_git_location }}/fuzzdb"
    update: yes

- name: Create FuzzDB symlink
  file:
    state: link
    src: "{{ wordlist_git_location }}/fuzzdb"
    path: "{{ wordlist_path }}/fuzzdb"

- name: Download SecLists
  become: true
  git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: "{{ wordlist_git_location }}/SecLists"
    update: yes

- name: Create SecLists symlink
  file:
    state: link
    src: "{{ wordlist_git_location }}/SecLists"
    path: "{{ wordlist_path }}/SecLists"
